config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:create]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  has_many_attached :images
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :products, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :role, presence: true, inclusion: { in: %w[merchant customer] }

  def merchant?
    role == 'merchant'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    redirect_to login_path unless logged_in?
  end

  def require_merchant
    if !logged_in? || current_user.role != 'merchant'
      flash.alert = 'You do not have permissions to access this feature!'
      redirect_to root_path
    end
  end

  def require_customer
    if !logged_in? || current_user.role != 'customer'
      flash.alert = 'You do not have permissions to access this feature!'
      redirect_to root_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_merchant, only: %i[ new create edit update destroy ]
  before_action :set_current_user_product, only: %i[ edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_current_user_product
      @product = current_user.products.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, images: [])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in!"
    else
      flash[:alert] = "Email or password is invalid"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Account created successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to 'Products', root_path, class: "link" %></li>
        <% if logged_in? %>
          <% if current_user.merchant? %>
            <li><%= link_to 'New Product', new_product_path, class: "link" %></li>
          <% end %>
          <li>Logged in as <u><%= current_user.email %></u></li>
          <li><%= link_to 'Logout', logout_path, data: { turbo_method: :delete }, class: "link" %></li>
        <% else %>
          <li><%= link_to 'Login', login_path, class: "link" %></li>
          <li><%= link_to 'Sign Up', signup_path, class: "link" %></li>
        <% end %>
      </ul>
    </nav>
    <main class="container mt-10">
      <% if notice %>
        <p class="text-green-500 mb-5"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="text-red-500 mb-5"><%= alert %></p>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :images, style: "display: block" %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<article id="<%= dom_id product %>" class="mt-5 flex">
  <%# Show image %>
  <% if product.images.attached? %>
    <%= image_tag product.images.first, alt: product.name, class: 'flex-none w-32 h-32 object-cover' %>
  <% else %>
    <%= image_tag 'placeholder-image.png', alt: 'No image available', class: 'flex-none w-32 h-32 object-cover' %>
  <% end %>

  <%# Product Info %>
  <div class="flex-initial p-5">
    <p>
      <strong>Name:</strong>
      <%= product.name %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= product.description %>
    </p>
    <p>
      <strong>Price:</strong>
      <%= product.price %>
    </p>
    <%# Conditionally show the 'show this product' button %>
    <% if local_assigns[:show_full] %>
      <div class="mt-1.5">
        <%= link_to "Edit this product", edit_product_path(@product), class: "btn" %> 
        <%= button_to "Destroy this product", @product, method: :delete, class: "btn", form_class: "inline-block" %>
      </div>
    <% else %>
      <p>
        <%= link_to "Show this product", product, class: "btn" %>
      </p>
    <% end %>
  </div>

</article>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product, show_full: false %>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product, show_full: true %>

app/views/users/new.html.erb
<div>
  <%= form_with model: @user do |form| %>
    <% if @user.errors.any? %>
      <div style="color: red">
        <ul>
          <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div>
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>
    <div>
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>
    <div>
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
    </div>
    <div>
      <%= form.label :role %>
      <%= form.select :role, options_for_select([['Merchant', 'merchant'], ['Customer', 'customer']]) %>
    </div>
    <div>
      <%= form.submit "Sign Up" %>
    </div>
  <% end %>

</div>